//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_delivery_tmp_header
    {
        public int id { get; set; }
        public int contract_header_id { get; set; }
        public int contract_detail_id { get; set; }
        public int created_by { get; set; }
        public System.DateTime created_time { get; set; }
        public bool delete_flag { get; set; }
        public Nullable<int> label_id { get; set; }
        public string OrderNum { get; set; }
        public Nullable<bool> CW_checked { get; set; }
        public Nullable<bool> CZ_checked { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> DeliverTime { get; set; }
    
        public virtual CRM_contract_detail CRM_contract_detail { get; set; }
        public virtual CRM_contract_header CRM_contract_header { get; set; }
    }
}
