//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ehr_postday
    {
        public long id { get; set; }
        public string number { get; set; }
        public string name { get; set; }
        public long employee { get; set; }
        public int department { get; set; }
        public string departmentname { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> time1 { get; set; }
        public Nullable<System.DateTime> time2 { get; set; }
        public Nullable<System.DateTime> time3 { get; set; }
        public Nullable<System.DateTime> time4 { get; set; }
        public Nullable<System.DateTime> time5 { get; set; }
        public Nullable<System.DateTime> time6 { get; set; }
        public Nullable<System.DateTime> time7 { get; set; }
        public Nullable<System.DateTime> time8 { get; set; }
        public Nullable<System.DateTime> time9 { get; set; }
        public Nullable<System.DateTime> time10 { get; set; }
        public Nullable<System.DateTime> time11 { get; set; }
        public Nullable<System.DateTime> time12 { get; set; }
        public Nullable<short> more { get; set; }
        public Nullable<int> count { get; set; }
    }
}
