//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ehr_employee
    {
        public int id { get; set; }
        public string number { get; set; }
        public string name { get; set; }
        public string user { get; set; }
        public string password { get; set; }
        public Nullable<short> @lock { get; set; }
        public int department { get; set; }
        public string departmentname { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string namecard { get; set; }
        public string nation { get; set; }
        public string birthplace { get; set; }
        public string education { get; set; }
        public string bankaccount { get; set; }
        public string tel { get; set; }
        public string accountlocation { get; set; }
        public string hometel { get; set; }
        public string homeaddress { get; set; }
        public short status { get; set; }
        public string jobs { get; set; }
        public Nullable<System.DateTime> jobtime { get; set; }
        public string socialsecurity { get; set; }
        public string photo { get; set; }
        public string mark { get; set; }
        public string marriage { get; set; }
        public string title { get; set; }
        public string other { get; set; }
        public string groupname { get; set; }
        public Nullable<int> group { get; set; }
        public string branchname { get; set; }
        public string branch { get; set; }
        public Nullable<System.DateTime> officialtime { get; set; }
        public Nullable<System.DateTime> quitdate { get; set; }
        public string shifts { get; set; }
        public Nullable<System.DateTime> lawdate { get; set; }
        public Nullable<int> level { get; set; }
        public string leveltext { get; set; }
        public string roledepartment { get; set; }
        public string roledepartmentname { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<byte> salary_type { get; set; }
        public Nullable<decimal> society_insure { get; set; }
    }
}
