//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ehr_department
    {
        public int id { get; set; }
        public string name { get; set; }
        public int parent { get; set; }
        public int son { get; set; }
        public string maps { get; set; }
        public string number { get; set; }
        public string charparent { get; set; }
    }
}
