//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ehr_sum
    {
        public long id { get; set; }
        public string number { get; set; }
        public string name { get; set; }
        public long employee { get; set; }
        public int department { get; set; }
        public string departmentname { get; set; }
        public System.DateTime d_start { get; set; }
        public System.DateTime d_end { get; set; }
        public Nullable<System.DateTime> registration { get; set; }
        public Nullable<System.DateTime> positive { get; set; }
        public Nullable<float> rest { get; set; }
        public Nullable<int> belate { get; set; }
        public Nullable<int> leaveearly { get; set; }
        public Nullable<int> absenteeism { get; set; }
        public Nullable<int> leave { get; set; }
        public Nullable<int> overtime { get; set; }
        public Nullable<int> workovertime { get; set; }
        public Nullable<int> holidayovertime { get; set; }
        public Nullable<int> workingtime { get; set; }
        public Nullable<int> shouldworkingtime { get; set; }
        public Nullable<float> shouldworkingday { get; set; }
        public Nullable<float> workingday { get; set; }
        public Nullable<float> leaveday { get; set; }
        public Nullable<int> leavenumber { get; set; }
        public Nullable<int> belatenumber { get; set; }
        public Nullable<int> leaveearlynumber { get; set; }
        public Nullable<int> absenteeismnumber { get; set; }
        public Nullable<int> replacementnumber { get; set; }
        public string mark { get; set; }
        public string leaverecord { get; set; }
        public string d1 { get; set; }
        public string d2 { get; set; }
        public string d3 { get; set; }
        public string d4 { get; set; }
        public string d5 { get; set; }
        public string d6 { get; set; }
        public string d7 { get; set; }
        public string d8 { get; set; }
        public string d9 { get; set; }
        public string d10 { get; set; }
        public string d11 { get; set; }
        public string d12 { get; set; }
        public string d13 { get; set; }
        public string d14 { get; set; }
        public string d15 { get; set; }
        public string d16 { get; set; }
        public string d17 { get; set; }
        public string d18 { get; set; }
        public string d19 { get; set; }
        public string d20 { get; set; }
        public string d21 { get; set; }
        public string d22 { get; set; }
        public string d23 { get; set; }
        public string d24 { get; set; }
        public string d25 { get; set; }
        public string d26 { get; set; }
        public string d27 { get; set; }
        public string d28 { get; set; }
        public string d29 { get; set; }
        public string d30 { get; set; }
        public string d31 { get; set; }
        public Nullable<int> early { get; set; }
        public Nullable<int> @in { get; set; }
        public Nullable<int> late { get; set; }
        public string user { get; set; }
    }
}
