//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Times
    {
        public HR_Times()
        {
            this.HR_WorkTime = new HashSet<HR_WorkTime>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Department { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<System.DateTime> d_start { get; set; }
        public Nullable<System.DateTime> d_end { get; set; }
        public Nullable<int> workingtime { get; set; }
        public Nullable<int> shouldworkingtime { get; set; }
        public Nullable<float> shouldworkingday { get; set; }
        public Nullable<float> workingday { get; set; }
        public string d1 { get; set; }
        public string d2 { get; set; }
        public string d3 { get; set; }
        public string d4 { get; set; }
        public string d5 { get; set; }
        public string d6 { get; set; }
        public string d7 { get; set; }
        public string d8 { get; set; }
        public string d9 { get; set; }
        public string d10 { get; set; }
        public string d11 { get; set; }
        public string d12 { get; set; }
        public string d13 { get; set; }
        public string d14 { get; set; }
        public string d15 { get; set; }
        public string d16 { get; set; }
        public string d17 { get; set; }
        public string d18 { get; set; }
        public string d19 { get; set; }
        public string d20 { get; set; }
        public string d21 { get; set; }
        public string d22 { get; set; }
        public string d23 { get; set; }
        public string d24 { get; set; }
        public string d25 { get; set; }
        public string d26 { get; set; }
        public string d27 { get; set; }
        public string d28 { get; set; }
        public string d29 { get; set; }
        public string d30 { get; set; }
        public string d31 { get; set; }
        public string WordDay { get; set; }
        public string TopMonthTX { get; set; }
        public string MonthTX { get; set; }
        public string TotalTX { get; set; }
    
        public virtual ICollection<HR_WorkTime> HR_WorkTime { get; set; }
    }
}
