//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_inventories
    {
        public INV_inventories()
        {
            this.INV_labels = new HashSet<INV_labels>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public byte type { get; set; }
        public string address { get; set; }
        public string remark { get; set; }
        public System.DateTime created_time { get; set; }
        public bool delete_flag { get; set; }
    
        public virtual ICollection<INV_labels> INV_labels { get; set; }
    }
}
