//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_product_SN
    {
        public SYS_product_SN()
        {
            this.SYS_product = new HashSet<SYS_product>();
        }
    
        public int id { get; set; }
        public string SN { get; set; }
        public string name { get; set; }
        public string remark { get; set; }
        public System.DateTime created_time { get; set; }
        public bool delete_flag { get; set; }
    
        public virtual ICollection<SYS_product> SYS_product { get; set; }
        public virtual SYS_product_SN SYS_product_SN1 { get; set; }
        public virtual SYS_product_SN SYS_product_SN2 { get; set; }
    }
}
