//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XNERPEntities : DbContext
    {
        public XNERPEntities()
            : base("name=XNERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<INV_wood_type> INV_wood_type { get; set; }
        public DbSet<SYS_colors> SYS_colors { get; set; }
        public DbSet<SYS_product_area> SYS_product_area { get; set; }
        public DbSet<SYS_product> SYS_product { get; set; }
        public DbSet<SYS_product_SN> SYS_product_SN { get; set; }
        public DbSet<CRM_contract_detail> CRM_contract_detail { get; set; }
        public DbSet<CRM_contract_header> CRM_contract_header { get; set; }
        public DbSet<INV_labels> INV_labels { get; set; }
        public DbSet<INV_inventories> INV_inventories { get; set; }
    }
}
