//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XNGYPEntities : DbContext
    {
        public XNGYPEntities()
            : base("name=XNGYPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<WorkLogs> WorkLogs { get; set; }
        public DbSet<XNGYP_Menu> XNGYP_Menu { get; set; }
        public DbSet<XNGYP_Role> XNGYP_Role { get; set; }
        public DbSet<XNGYP_Customers> XNGYP_Customers { get; set; }
        public DbSet<Contract_Detail> Contract_Detail { get; set; }
        public DbSet<Contract_Header> Contract_Header { get; set; }
        public DbSet<XNGYP_Products> XNGYP_Products { get; set; }
        public DbSet<XNGYP_Products_SN> XNGYP_Products_SN { get; set; }
        public DbSet<XNGYP_Products_WorkFrom> XNGYP_Products_WorkFrom { get; set; }
        public DbSet<XNGYP_Products_WorkFrom_Price> XNGYP_Products_WorkFrom_Price { get; set; }
        public DbSet<INV_Name> INV_Name { get; set; }
        public DbSet<INV_Name_Type> INV_Name_Type { get; set; }
        public DbSet<XNGYP_INV_Labels> XNGYP_INV_Labels { get; set; }
        public DbSet<XNGYP_INV_Semi> XNGYP_INV_Semi { get; set; }
        public DbSet<XNGYP_WIP_PreCast> XNGYP_WIP_PreCast { get; set; }
        public DbSet<XNGYP_WorkOrder> XNGYP_WorkOrder { get; set; }
    }
}
