//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class XNGYP_INV_Semi
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> ProductSNId { get; set; }
        public string ProductSN { get; set; }
        public Nullable<int> WoodId { get; set; }
        public string WoodName { get; set; }
        public Nullable<int> ColorId { get; set; }
        public string ColorName { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> INVId { get; set; }
        public Nullable<System.DateTime> InputDate { get; set; }
        public Nullable<int> InputUserId { get; set; }
        public string InputUserName { get; set; }
        public Nullable<System.DateTime> OutDate { get; set; }
        public Nullable<int> OutUserId { get; set; }
        public string OutUserName { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CDetailId { get; set; }
        public Nullable<int> WPCastId { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<int> WorkOrderId { get; set; }
        public Nullable<int> FatherId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> Grade { get; set; }
    
        public virtual INV_Name INV_Name { get; set; }
        public virtual XNGYP_Products_SN XNGYP_Products_SN { get; set; }
        public virtual XNGYP_Products_SN XNGYP_Products_SN1 { get; set; }
    }
}
