//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class XNGYP_Products_SN
    {
        public XNGYP_Products_SN()
        {
            this.XNGYP_Products = new HashSet<XNGYP_Products>();
            this.XNGYP_INV_Labels = new HashSet<XNGYP_INV_Labels>();
            this.XNGYP_Products_SN1 = new HashSet<XNGYP_Products_SN>();
            this.XNGYP_INV_Labels1 = new HashSet<XNGYP_INV_Labels>();
            this.XNGYP_Products1 = new HashSet<XNGYP_Products>();
        }
    
        public int Id { get; set; }
        public string SN { get; set; }
        public string name { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> created_time { get; set; }
        public Nullable<bool> delete_flag { get; set; }
        public Nullable<int> FatherId { get; set; }
    
        public virtual ICollection<XNGYP_Products> XNGYP_Products { get; set; }
        public virtual ICollection<XNGYP_INV_Labels> XNGYP_INV_Labels { get; set; }
        public virtual ICollection<XNGYP_Products_SN> XNGYP_Products_SN1 { get; set; }
        public virtual XNGYP_Products_SN XNGYP_Products_SN2 { get; set; }
        public virtual ICollection<XNGYP_INV_Labels> XNGYP_INV_Labels1 { get; set; }
        public virtual ICollection<XNGYP_Products> XNGYP_Products1 { get; set; }
    }
}
