//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class XNGYP_WorkFrom
    {
        public int Id { get; set; }
        public Nullable<int> WorkOrderId { get; set; }
        public Nullable<int> GXId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> exp_begin_date { get; set; }
        public Nullable<System.DateTime> exp_end_date { get; set; }
        public Nullable<System.DateTime> act_begin_date { get; set; }
        public Nullable<System.DateTime> act_end_date { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<int> CheckedUserId { get; set; }
        public string CheckedUser { get; set; }
        public Nullable<System.DateTime> CheckedDate { get; set; }
        public string CheckedReason { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> WoodId { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    
        public virtual XNGYP_WorkOrder XNGYP_WorkOrder { get; set; }
        public virtual XNGYP_Products XNGYP_Products { get; set; }
    }
}
