//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class XNGYP_INV_Labels
    {
        public int Id { get; set; }
        public int ProductsId { get; set; }
        public Nullable<int> ProductsSNId { get; set; }
        public string SN { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Status { get; set; }
        public string WoodName { get; set; }
        public string Color { get; set; }
        public Nullable<int> INVId { get; set; }
        public Nullable<int> ContractDetailId { get; set; }
        public Nullable<int> WIPContractIid { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<System.DateTime> InputDateTime { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Company { get; set; }
        public string Address { get; set; }
        public string WebSite { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<int> WoodId { get; set; }
        public Nullable<int> ColorId { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<int> Grade { get; set; }
        public string Picture { get; set; }
        public string ProductSN { get; set; }
        public Nullable<int> FatherId { get; set; }
        public Nullable<int> WorkOrderId { get; set; }
    
        public virtual INV_Name INV_Name { get; set; }
        public virtual XNGYP_Products XNGYP_Products { get; set; }
        public virtual XNGYP_Products_SN XNGYP_Products_SN { get; set; }
        public virtual XNGYP_Products_SN XNGYP_Products_SN1 { get; set; }
    }
}
