//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class XNGYP_Products_WorkFrom_Price
    {
        public int Id { get; set; }
        public int ProductsId { get; set; }
        public string WorkFrom { get; set; }
        public Nullable<int> WorkFromId { get; set; }
        public Nullable<decimal> WorkFromPrice { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    
        public virtual XNGYP_Products XNGYP_Products { get; set; }
        public virtual XNGYP_Products_WorkFrom XNGYP_Products_WorkFrom { get; set; }
    }
}
